import path from 'path';
import fs from 'fs';
import { createRequire } from 'module';
import { Resolver } from "@parcel/plugin";
const reactVersion = require("react-dom/package.json").version;
import { default as NodeResolver } from "@parcel/node-resolver-core";
// @ts-ignore
import { isGlob, glob, normalizeSeparators, relativePath } from '@parcel/utils';

const REACT_MAJOR_VERSION = parseInt(reactVersion.split('.')[0], 10);

// --- Storybook globals externals (Approach B: codegen-time enumeration) ---
// Match upstream Vite's behavior: at resolver-startup, read storybook's
// `globalsNameReferenceMap` from `node_modules/storybook/dist/preview/globals.js`,
// then for each (specifier -> globalName) pair generate a synthetic ESM module
// that re-exports the named bindings from `globalThis.__STORYBOOK_MODULE_*__`.
// The synthetic file is written once to `node_modules/.cache/sb-parcel-externals/`
// so it is visible in the network tab and is re-used across resolve() calls.

const _require = createRequire(__filename);

interface ExternalEntry {
  filePath: string;
  // Whether we used the Approach B (named re-export) or Approach A (CJS interop) fallback
  approach: 'B' | 'A';
}

function buildExternalsCache(): Record<string, ExternalEntry> {
  const result: Record<string, ExternalEntry> = {};
  const cacheDir = path.join(
    _require.resolve('storybook/package.json'),
    '..', '..', '.cache', 'sb-parcel-externals'
  );
  fs.mkdirSync(cacheDir, { recursive: true });

  // Read storybook's canonical map at startup; do not hardcode.
  let globalsNameReferenceMap: Record<string, string>;
  try {
    const globalsModulePath = _require.resolve('storybook/internal/preview/globals');
    // Use dynamic import via createRequire-style; storybook ships ESM here so
    // fall back to reading the JS source if require() can't load ESM.
    try {
      const mod = _require(globalsModulePath);
      globalsNameReferenceMap = mod.globalsNameReferenceMap;
    } catch {
      const src = fs.readFileSync(globalsModulePath, 'utf8');
      // Match the object literal between `var globalsNameReferenceMap = {` and `}`
      const m = src.match(/globalsNameReferenceMap\s*=\s*(\{[\s\S]*?\})\s*,/);
      if (!m) throw new Error('Could not parse globalsNameReferenceMap from ' + globalsModulePath);
      // Parse it as JSON-ish (keys are quoted strings, values are quoted strings,
      // but there's a trailing comment line). Strip line comments first.
      const cleaned = m[1].replace(/\/\/.*$/gm, '').replace(/,\s*\}/, '}');
      // eslint-disable-next-line no-new-func
      globalsNameReferenceMap = (new Function('return ' + cleaned))();
    }
  } catch (e) {
    throw new Error(
      `[parcel-resolver-storybook] Failed to load storybook globalsNameReferenceMap: ${(e as Error).message}`
    );
  }

  for (const [specifier, globalName] of Object.entries(globalsNameReferenceMap)) {
    const safeKey = specifier.replace(/[\/@]/g, '_');
    const filePath = path.join(cacheDir, `${safeKey}.js`);

    // Hardcode @storybook/global since its only export is `global`.
    if (specifier === '@storybook/global') {
      const code =
        `// Generated by @parcel/resolver-storybook\n` +
        `// Re-exports ${specifier} from globalThis.${globalName}\n` +
        `const { global } = globalThis.${globalName};\n` +
        `export { global };\n` +
        `export default globalThis.${globalName};\n`;
      fs.writeFileSync(filePath, code);
      result[specifier] = { filePath, approach: 'B' };
      continue;
    }

    // Approach B: enumerate named exports via require() and codegen
    // a `const { ... } = globalThis.X; export { ... };` synthetic module.
    let namedExports: string[] | null = null;
    try {
      const mod = _require(specifier);
      if (mod && typeof mod === 'object') {
        // Filter out 'default' and '__esModule' (CJS interop marker that some
        // bundles attach as an enumerable own property).
        namedExports = Object.keys(mod).filter(k => k !== 'default' && k !== '__esModule');
      }
    } catch {
      namedExports = null;
    }

    if (namedExports && namedExports.length > 0) {
      // Filter out reserved/invalid identifiers just in case
      const valid = namedExports.filter(n => /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(n));
      const list = valid.join(', ');
      const code =
        `// Generated by @parcel/resolver-storybook\n` +
        `// Re-exports ${specifier} from globalThis.${globalName}\n` +
        `const { ${list} } = globalThis.${globalName};\n` +
        `export { ${list} };\n` +
        `export default globalThis.${globalName};\n`;
      fs.writeFileSync(filePath, code);
      result[specifier] = { filePath, approach: 'B' };
    } else {
      // Approach A fallback: emit CJS interop. Used when require() couldn't
      // enumerate the module (e.g. ESM-only with no enumerable exports via require).
      const code =
        `// Generated by @parcel/resolver-storybook (Approach A fallback)\n` +
        `// Could not enumerate named exports for ${specifier}; using CJS interop.\n` +
        `module.exports = globalThis.${globalName};\n`;
      fs.writeFileSync(filePath, code);
      result[specifier] = { filePath, approach: 'A' };
    }
  }

  return result;
}

// Generate cache files ONCE at module load (resolver-instance creation).
const STORYBOOK_EXTERNALS = buildExternalsCache();

module.exports = new Resolver({
  async resolve({ dependency, options, specifier, pipeline, logger }) {
    // Storybook globals: externalize runtime modules to globalThis.__STORYBOOK_MODULE_*__
    // Runs before the other branches when using the default pipeline.
    if (pipeline == null && Object.prototype.hasOwnProperty.call(STORYBOOK_EXTERNALS, specifier)) {
      const entry = STORYBOOK_EXTERNALS[specifier];
      return {
        filePath: entry.filePath,
        priority: 'sync',
        pipeline: null,
      };
    }

    // Workaround for interop issue
    if (specifier === "react-dom/client" && REACT_MAJOR_VERSION < 18) {
      return {
        filePath: __dirname + "/react.js",
        code: `
        export * from 'react-dom';
        export * as default from 'react-dom'
        `,
      };
    }

    // Resolve story entry globs. Storybook expects an object with relative paths from the process cwd as keys.
    // We do this in a resolver so that it invalidates the watcher when new stories are created.
    if (pipeline === 'story') {
      let sourceFile = dependency.resolveFrom ?? dependency.sourcePath!;
      let normalized = normalizeSeparators(path.resolve(path.dirname(sourceFile), atob(specifier)));
      let files = await glob(normalized, options.inputFS, {
        onlyFiles: true,
      });

      let cwd = process.cwd();
      let dir = path.dirname(sourceFile);
      let results = files.map(file => {
        let key = relativePath(cwd, file);
        let relative = relativePath(dir, file);
        return `  ${JSON.stringify(key)}: () => import(${JSON.stringify(relative)}),\n`;
      });

      return {
        filePath: path.join(
          dir,
          'stories.js'
        ),
        code: `module.exports = {\n${results.join('\n')}\n};\n`,
        invalidateOnFileCreate: [
          {glob: normalized}
        ],
        pipeline: null,
        priority: 'sync',
      };
    }
  },
});
