needs translations:
- changed-files:
  - any-glob-to-any-file: ['**/intl/*.json']

S2:
- changed-files:
  - any-glob-to-any-file: ['**/s2/**']

RAC:
- changed-files:
  - any-glob-to-any-file: ['**/react-aria-components/**', '**/@react-aria/**']

v3:
- all:
  - changed-files:
    - any-glob-to-any-file: '**/@react-spectrum/**'
    - all-globs-to-all-files: '!**/@react-spectrum/s2/**'
