nodeLinker: node-modules

packageExtensions:
  "@parcel/node-resolver-core@*":
    peerDependencies:
      "@parcel/core": ^2.12.0

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-4.2.2.cjs

plugins:
  - .yarn/plugins/plugin-nightly-prep.js
