changesetIgnorePatterns:
  - "**/*.test.*"
  - "**/*.md"
  - "**/test/**"

nodeLinker: node-modules

packageExtensions:
  "@parcel/node-resolver-core@*":
    peerDependencies:
      "@parcel/core": ^2.12.0

plugins:
  - .yarn/plugins/plugin-nightly-prep.js

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-4.13.0.cjs
