export const commonDeclarations = [
  'display:flex',
  'position:absolute',
  'position:relative',
  'width:100%',
  'display:block',
  'display:none',
  'display:inline-block',
  'overflow:hidden',
  'align-items:center',
  'padding:0',
  'margin:0',
  'text-align:center',
  'color:#fff',
  'font-weight:400',
  'left:0',
  'height:100%',
  'top:0',
  'cursor:pointer',
  'text-decoration:none',
  'flex-direction:column',
  'content:""',
  'justify-content:center',
  'box-sizing:border-box',
  '-webkit-box-direction:normal',
  'font-weight:700',
  'right:0',
  '-webkit-box-align:center',
  '-webkit-box-orient:vertical',
  'white-space:nowrap',
  'font-weight:500',
  'bottom:0',
  'font-size:14px',
  'flex-direction:row',
  'border:0',
  '-webkit-align-items:center',
  'background-color:#fff',
  'margin-bottom:0',
  'opacity:0',
  'opacity:1',
  'font-family:"Roboto", "Arial", sans-serif',
  'margin-top:0',
  'float:left',
  'vertical-align:middle',
  'background-color:transparent',
  'pointer-events:none',
  'text-align:left',
  'height:auto',
  'background-repeat:no-repeat',
  'font-size:16px',
  'font-size:12px',
  '-webkit-flex-direction:column',
  '-webkit-box-pack:center',
  'z-index:1',
  '-webkit-box-orient:horizontal',
  'margin-left:0',
  'border:none',
  'width:auto',
  '-webkit-flex-direction:row',
  'text-overflow:ellipsis',
  'padding-left:0',
  '-ms-flex-align:center',
  'margin-right:0',
  'text-decoration:underline',
  'border-radius:50%',
  'color:#000',
  'text-transform:uppercase',
  '-webkit-justify-content:center',
  'outline:none',
  'border-radius:4px',
  '-webkit-box-flex:1',
  'justify-content:space-between',
  'box-shadow:none',
  'max-width:100%',
  'margin:0 auto',
  'font-weight:600',
  'top:50%',
  'outline:0',
  'font-style:normal',
  'background:#fff',
  'display:inline-flex',
  'font-size:1.4rem',
  'height:24px',
  'flex:1',
  'position:fixed',
  'flex-wrap:wrap',
  'list-style:none',
  'color:inherit',
  'visibility:hidden',
  'left:50%',
  'width:0',
  'height:20px',
  'height:0',
  'display:inline',
  'line-height:20px',
  'font-size:0.875rem',
  'min-width:0',
  'font-size:1rem',
  'border-radius:8px',
  'line-height:2rem',
  'flex-grow:1',
  'float:right',
  '-ms-flex-direction:column',
  'height:40px',
  '-ms-flex-pack:center',
  'vertical-align:top',
  'color:var(--yt-spec-text-primary)',
  'font-weight:bold',
  'padding-right:0',
  'white-space:normal',
  'height:16px',
  'margin-right:8px',
  'line-height:1.5',
  'text-align:right',
  'padding-bottom:0',
  'display:-webkit-box',
  'cursor:default',
  'margin-top:8px',
  'height:1px',
  'flex-shrink:0',
  'font-size:1.2rem',
  'font-size:13px',
  'width:24px',
  'border-radius:2px',
  'z-index:2',
  'padding-top:0',
  'font-size:18px',
  'line-height:1',
  'width:16px',
  'margin-bottom:8px',
  'clear:both',
  'align-items:flex-start',
  'margin-right:16px',
  'border-radius:0',
  '-webkit-flex:1',
  'margin-left:auto',
  'width:20px',
  'font-weight:normal',
  'color:#333',
  'height:32px',
  'font-size:20px',
  'border-style:solid',
  'transition-duration:75ms',
  'color:var(--yt-spec-text-secondary)',
  '-webkit-box-sizing:border-box',
  '-webkit-transition-duration:75ms',
  'visibility:visible',
  'line-height:1.8rem',
  'margin-bottom:10px',
  'text-transform:none',
  'border-radius:3px',
  'margin-bottom:16px',
  'width:1px',
  'overflow:visible',
  'background:none',
  'user-select:none',
  'z-index:0',
  'line-height:24px',
  'display:grid',
  'margin-top:16px',
  'line-height:normal',
  'margin-left:16px',
  'background:transparent',
  '-webkit-font-smoothing:antialiased',
  'background:0 0',
  'padding-left:28px',
  'justify-content:flex-end',
  'margin-left:8px',
  'border-color:transparent',
  'justify-content:flex-start',
  'display:table',
  '-webkit-user-select:none',
  'margin-top:4px',
  'height:48px',
  'margin-right:auto',
  '-webkit-box-pack:justify',
  'margin-right:10px',
  'margin:auto',
  'float:none',
  'width:40px',
  'margin-bottom:20px',
  'font-size:24px',
  'letter-spacing:0',
  'line-height:0',
  'padding-left:16px',
  'font-size:1.6rem',
  'font-size:15px',
  'line-height:16px',
  'font-size:11px',
  'min-height:0',
  '-webkit-appearance:none',
  '-webkit-box-flex:0',
  'font-size:inherit',
  'margin-bottom:12px',
  'color:var(--channel-color)',
  'font-size:0',
  '-webkit-justify-content:space-between',
  'left:auto',
  'z-index:-1',
  '-webkit-flex-basis:0.0px',
  'flex-basis:0.0px',
  'border-bottom:none',
  'align-self:center',
  'font-size:0.75rem',
  'position:static',
  'border-bottom:0',
  'letter-spacing:normal',
  'overflow:auto',
  '-webkit-line-clamp:2',
  'font-family:inherit',
  'font-style:italic',
  'margin-top:10px',
  'padding-right:16px',
  'line-height:18px',
  'height:12px',
  'margin-bottom:24px',
  'height:30px',
  'margin-top:12px',
  'height:36px',
  'margin-right:4px',
  'background-size:cover',
  'white-space:pre-wrap',
  'box-sizing:content-box',
  'height:28px',
  'object-fit:cover',
  'transform:translate(-50%, -50%)',
  'width:32px',
  'margin-bottom:4px',
  '-webkit-text-decoration:none',
  'padding:8px',
  '-moz-osx-font-smoothing:grayscale',
  'color:var(--color_secondary)',
  'border-radius:12px',
  'opacity:0.5',
  'margin-left:4px',
  'list-style-type:none',
  'height:56px',
  'padding:16px',
  'border:0 solid black',
  'margin-top:20px',
  'padding-top:8px',
  'height:14px',
  'right:auto',
  'content:" "',
  '-ms-flex-direction:row',
  'height:18px',
  'border-width:1px',
  'overflow-y:auto',
  '-moz-user-select:none',
  'line-height:1.25',
  '-webkit-flex-grow:1',
  'font-size:10px',
  'height:35px',
  'word-wrap:break-word',
  'line-height:2.2rem',
  'padding:10px',
  'vertical-align:baseline',
  'background-image:none',
  'transition:opacity 0.15s linear',
  'font-weight:300',
  'overflow-wrap:break-word',
  '-webkit-line-clamp:1',
  'padding-left:8px',
  'background-color:rgba(0, 0, 0, 0)',
  'transform:translatey(-50%)',
  '-webkit-transition:opacity 0.15s linear',
  'color:#222',
  'width:12px',
  'color:#FFF',
  'transform:none',
  'flex:1 1 auto',
  'z-index:10',
  'background-color:#000',
  'max-width:none',
  'font-size:1.125rem',
  'line-height:inherit',
  'flex:none',
  'margin-right:12px',
  '-ms-user-select:none',
  'border-radius:5px',
  'margin-bottom:5px',
  'font-size:1em',
  'margin-top:24px',
  'font-size:1.5rem',
  'cursor:not-allowed',
  '-webkit-flex-shrink:0',
  'overflow-x:hidden',
  'margin-bottom:15px',
  'width:35px',
  'padding-bottom:8px',
  'height:10px',
  'line-height:1.3',
  'border-width:0',
  'width:50%',
  '-webkit-flex-wrap:wrap',
  'width:48px',
  'padding-right:8px',
  'border-top:0',
  'background-size:contain',
  'height:50px',
  'padding-left:10px',
  '-ms-flex-pack:justify',
  'padding-right:12px',
  'display:table-cell',
  'z-index:3',
  'fill:#fff',
  '-webkit-box-pack:end',
  'line-height:22px',
  'line-height:1.2',
  'align-self:flex-start',
  '-ms-flex-wrap:wrap',
  'padding-right:10px',
  'transition:none',
  'width:18px',
  'line-height:26px',
  'border-radius:6px',
  'appearance:none',
  'background-size:20px',
  'line-height:14px',
  '-moz-box-align:center',
  'top:auto',
  'border-radius:16px',
  'margin-right:5px',
  'margin-top:5px',
  'margin:-1px',
  'word-break:break-word',
  'padding-left:38px',
  'color:#555',
  '-webkit-justify-content:flex-end',
  'background-position:0 13px',
  'background-position:10px 8px',
  'background-position:7px 3px',
  'background-size:35px',
  'background-position:0 6px',
  'margin-left:10px',
  'background-position:50%',
  '-webkit-flex:none',
  '-webkit-box-align:start',
  'font-size:1.25rem',
  'width:36px',
  'padding-left:12px',
  'align-items:flex-end',
  'padding-bottom:16px',
  'color:#666',
  'border-collapse:collapse',
  'color:#1E2124',
  'height:60px',
  'width:30px',
  'zoom:1',
  'vertical-align:0',
  'line-height:1.5rem',
  'color:#0f0f0f',
  'margin-top:2px',
  'border:1px solid transparent',
  'pointer-events:auto',
  'line-height:28px',
  'background-position:center',
  'flex:0 0 auto',
  '-moz-box-sizing:border-box',
  'font-size:1.8rem',
  'outline-offset:2px',
  'margin-left:5px',
  'padding-top:16px',
  'color:rgb(95, 99, 104)',
  'width:10px',
  'max-height:100%',
  'margin-bottom:1rem',
  'padding:12px',
  'background:#000',
  'content:var(--tw-content)',
  '-webkit-box-shadow:none',
  'font-weight:900',
  'font:inherit',
  'flex-wrap:nowrap',
  'color:transparent',
  'vertical-align:bottom',
  'height:26px',
  'align-items:stretch',
  'padding-left:20px',
  'padding:0 16px',
  'border-color:#fff',
  'margin-left:12px',
  'padding:4px',
  'opacity:0.8',
  'height:64px',
  'color:#212121',
  'font-family:ProximaNova',
  'margin-right:24px',
  '-webkit-align-items:flex-start',
  'padding-right:24px',
  '-ms-flex:1',
  'padding-left:24px',
  'color:var(--bui_color_white)',
  '-webkit-align-self:center',
  '-o-object-fit:cover',
  'border-radius:100%',
  'align-self:stretch',
  'width:14px',
  'top:1px',
  'font-size:2rem',
  '-webkit-box-pack:start',
  'width:100vw',
  'height:22px',
  'margin-left:24px',
  'bottom:auto',
  'direction:ltr',
  'line-height:30px',
  'color:#999',
  '-webkit-tap-highlight-color:transparent',
  'height:8px',
  '-ms-flex-positive:1',
  'width:8px',
  'padding:20px',
  'height:15px',
  'gap:8px',
  'fill:currentColor',
  'padding:0 24px',
  'padding-top:24px',
  'padding-top:4px',
  'border-radius:20px',
  'top:2px',
  'top:-1px',
  'position:sticky',
  'width:100px',
  'background-size:100%',
  'padding:5px',
  'height:2px',
  'border-spacing:0',
  'letter-spacing:-0.01em',
  'transform:translatex(-50%)',
  'margin-top:6px',
  'color:rgba(0, 0, 0, 0.87)',
  'top:100%',
  'border-top:none',
  'padding-bottom:24px',
  'width:28px',
  'z-index:100',
  'top:10px',
  'opacity:0.7',
  'padding-top:10px',
  'color:#606060',
  'top:8px',
  'transform:rotate(180deg)',
  'margin-right:20px',
  'padding-top:12px',
  'font-weight:800',
  'font-family:Roboto-Regular',
  '-moz-appearance:none',
  'font-size:17px',
  'padding-bottom:10px',
  'background-color:#eee',
  'right:10px',
  '-webkit-text-decoration:underline',
  'width:15px',
  'height:44px',
  'border-radius:inherit',
  'padding-left:5px',
  'margin-bottom:30px',
  'font-size:22px',
  'padding-bottom:12px',
  'padding-bottom:20px',
  'overflow-y:hidden',
  '-webkit-transform:translate(-50%, -50%)',
  'order:1',
  'color:#1D1D1B',
  '-ms-flex-negative:0',
  'flex-direction:row-reverse',
  'padding-bottom:4px',
  'font-size:32px',
  'width:300px',
  '-webkit-align-self:flex-start',
  'right:8px',
  'font-size:100%',
  'padding-right:auto',
  'padding-left:auto',
  'color:#586c8f',
  '-webkit-transform:none',
  'opacity:0.6',
  'width:60px',
  'color:#5f6368',
  'width:fit-content',
  'width:50px',
  'margin:8px 0',
  'margin-top:15px',
  'font-family:ProximaNovaCond, ProximaNovaCondFallback, sans-serif',
  'color:var(--color_white)',
  'width:200px',
  'height:72px',
  'font-family:Roboto, sans-serif',
  'color:var(--yt-spec-static-overlay-text-primary)',
  'line-height:32px',
  'opacity:var(--mdc-ripple-focus-opacity, 0.12)',
  'font-size:30px',
  'opacity:var(--mdc-ripple-hover-opacity, 0.04)',
  '--l_display:unset',
  'padding:24px',
  'width:80px',
  '-webkit-justify-content:flex-start',
  'padding-right:20px',
  'line-height:1.4',
  'background:#FFF',
  'color:var(--color_main)',
  '--comp-display:unset',
  'transform:rotate(45deg)',
  'border-radius:10px',
  'padding-top:5px',
  'padding:0 8px',
  'align-items:baseline',
  'font-size:28px',
  'color:#767676',
  'height:25px',
  'color:#202124',
  'border-top-right-radius:0',
  'padding:8px 0',
  'margin-bottom:-20px',
  'padding-left:4px',
  'top:5px',
  'width:64px',
  'color:#111',
  'order:2',
  'font-weight:inherit',
  'margin-top:32px',
  'line-height:2.6rem',
  'padding:0 12px',
  'border-top-left-radius:0',
  '-moz-box-pack:center',
  'height:100px',
  'clip:rect(1px, 1px, 1px, 1px)',
  'padding:0 10px',
  'text-align:start',
  'transform:translatey(0)',
  'transform:scale(1)',
  'overflow-x:auto',
  'line-height:40px',
  'line-height:1.6',
  'font-family:var(--spl-font-family-body-primary), var(--spl-font-family-body-secondary)',
  'margin-bottom:2px',
  'text-transform:capitalize',
  'top:4px',
  'background-position:0 0',
  'line-height:1.25rem',
  'opacity:0.4',
  'background-color:#FFF',
  'margin-left:20px',
  'object-fit:contain',
  'height:100vh',
  '-webkit-touch-callout:none',
  'margin-bottom:0.5rem',
  'overflow-y:scroll',
  'font-size:2.4rem',
  'color:#444',
  'margin-left:0%',
  'border-radius:24px',
  'margin-bottom:32px',
  'flex-grow:0',
  'width:26px',
  'border-bottom-left-radius:0',
  'margin-top:-1px',
  '-ms-flex-pack:start',
  'color:white',
  'padding-top:20px',
  'border-bottom-right-radius:0',
  'border:2px solid transparent',
  'padding:0 20px',
  'z-index:1000',
  'z-index:5',
  '-moz-box-direction:normal',
  'padding-top:2px',
  'color:#777',
  'scrollbar-width:none',
  'top:3px',
  'padding-left:15px',
  'color:#0097f5',
  'vertical-align:-20px',
  'margin-left:-8px',
  'margin-bottom:0%',
  'min-width:100%',
  'padding:10px 0',
  'height:17px',
  'right:16px',
  'gap:16px',
  'border:1px solid',
  'padding:15px',
  '-ms-flex:0 0 auto',
  'line-height:12px',
  'outline:2px solid #b2e',
  'margin-left:2px',
  'left:8px',
  'content:none',
  'margin-right:0%',
  'border-width:2px',
  'margin-bottom:6px',
  'letter-spacing:1px',
  'background-color:var(--channel-color)',
  'line-height:17px',
  'width:22px',
  'background-color:#f5f5f5',
  'color:rgb(32, 33, 36)',
  'align-self:start',
  'padding-bottom:2px',
  'transform:translatez(0)',
  'border-left:0',
  'color:#ccc',
  'padding-right:4px',
  'margin-top:-2px',
  'word-wrap:normal',
  'color:var(--gm3-sys-color-on-surface-variant, #444746)',
  'font-size:1.2em',
  'height:4px',
  'min-height:50px',
  'font-family:"YouTube Sans", "Roboto", sans-serif',
  'min-height:48px',
  'clip:rect(0, 0, 0, 0)',
  'letter-spacing:0.5px',
  'border:1px solid #ccc',
  'line-height:1.33',
  'line-height:19px',
  'width:25px',
  'right:12px',
  'border-style:none',
  '-moz-box-flex:1',
  'transform:scalex(-1)',
  'width:120px',
  'margin-bottom:40px',
  'line-height:1em',
  'margin-right:2px',
  'color:#212529',
  'align-self:flex-end',
  'margin-top:auto',
  '-ms-flex:1 1 auto',
  'line-height:1.428571',
  'font-family:"Google Sans", Roboto, Arial, sans-serif',
  'font-size:1.3rem',
  'border-radius:100px',
  'margin-top:1rem',
  'left:10px',
  'grid-area:1/1/2/2',
  '-ms-flex-pack:end',
  'background-position:center center',
  '-webkit-line-clamp:3',
  'padding-right:15px',
  'margin-top:30px',
  'min-height:100%',
  'height:6px',
  'left:16px',
  'color:rgba(0, 0, 0, 0.6)',
  '--source-text-decoration-thickness:2px',
  'color:#007FAA',
  'inset:0',
  'height:80px',
  '-ms-flex-align:start',
  'border-radius:0.25rem',
  'padding:8px 16px',
  'width:44px',
  'margin:0 4px',
  'top:-4px',
  'height:34px',
  'padding-bottom:5px',
  'max-width:99999px',
  'color:var(--yt-spec-call-to-action)',
  'pointer-events:all',
  'border-right:none',
  'margin-top:40px',
  'padding:0 4px',
  'margin-top:3px',
  'font-size:0.8125rem',
  'background-clip:padding-box',
  'left:-1px',
  'margin-bottom:7px',
  'width:max-content',
  'font-family:sans-serif',
  'vertical-align:text-bottom',
  'line-height:1rem',
  'z-index:4',
  'color:rgb(154, 160, 166)',
  'margin-right:6px',
  'top:12px',
  'width:25%',
  'opacity:0.3',
  'flex-shrink:1',
  'margin-left:3px',
  'background-color:inherit',
  'margin-left:6px',
  'will-change:transform',
  '-ms-transform:none',
  'height:1em',
  'line-height:1.1',
  'border-bottom:1px solid var(--yt-spec-10-percent-layer)',
  'justify-content:space-around',
  'left:100%',
  'line-height:15px',
  'top:16px',
  '-webkit-transform:translatey(-50%)',
  'height:1rem',
  'text-shadow:none',
  '-webkit-flex:1 1 auto',
  'padding-right:5px',
  'top:-2px',
  'min-height:40px',
  'padding:4px 0',
  'min-height:20px',
  'max-height:1.8rem',
  '-webkit-overflow-scrolling:touch',
  'right:20px',
  'line-height:3.2rem',
  'max-height:none',
  'border-right:0',
  'width:calc(100% - 16px)',
  'line-height:2.8rem',
  'padding:16px 0',
  'color:var(--gm3-sys-color-on-surface, #1f1f1f)',
  '-moz-box-orient:vertical',
  'color:rgb(60, 64, 67)',
  'font-family:Austin News, georgia, times, serif',
  'font-family:TimesModern-Bold, TimesModern-Bold-fallback, serif',
  'width:90%',
  'align-content:center',
  'margin-right:3px',
  'color:#333E48',
  '-webkit-box-align:end',
  'padding-left:6px',
  'font-family:GuardianTextSans, "Guardian Text Sans Web", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif',
  'font-family:"Proxima Nova", sans-serif',
  'width:17px',
  'background:0',
  'font-family:"Roboto-Regular", sans-serif',
  'margin-right:15px',
  'border:1px solid var(--yt-spec-10-percent-layer)',
  'padding:6px',
  'height:13px',
  'border:1px solid #ddd',
  'font-family:ABCFavorit, Arial, Helvetica, sans-serif',
  'left:20px',
  'background-color:#f8f8f8',
  'height:45px',
  'display:var(--l_display, var(--display, block))',
  'margin:10px 0',
  'margin:16px 0',
  'width:6px',
  'font-weight:200',
  'padding:1rem',
  'fill:currentcolor',
  'width:56px',
  'gap:4px',
  'border-left:none',
  '-ms-transform:translatey(-50%)',
  'width:160px',
  'height:200px',
  'margin-top:-4px',
  'height:19px',
  'margin-bottom:1.5rem',
  'min-height:32px',
  'color:var(--mdc-theme-on-surface, #000)',
  'margin:0 8px',
  'height:70px',
  'max-width:300px',
  'height:38px',
  'border:1px solid #fff',
  'padding:2px',
  'height:11px',
  'flex-basis:100%',
  'margin:20px 0',
  'background-color:initial',
  'flex:1 0 auto',
  'opacity:var(--mdc-ripple-press-opacity, 0.12)',
  'text-align:inherit',
  'overflow-x:scroll',
  'opacity:0.9',
  'padding-right:32px',
  'width:1rem',
  'padding:0 5px',
  'max-width:500px',
  'padding:4px 8px',
  '-webkit-transition:none',
  'min-width:20px',
  'width:210px',
  'margin-top:1px',
  'padding-left:40px',
  '-webkit-tap-highlight-color:rgba(0, 0, 0, 0)',
  'background-size:16px 16px',
  'padding:8px 12px',
  'outline-offset:-2px',
  'top:-5px',
  'border-left-width:0',
  'text-rendering:optimizeLegibility',
  'line-height:1.15',
  'padding:0 15px',
  'border-bottom:1px solid transparent',
  'line-height:36px',
  'right:5px',
  'border-radius:1px',
  'padding-top:3px',
  'padding:20px 0',
  'transform:scale(0)',
  'width:1em',
  'padding-top:6px',
  'fill:#000',
  'width:inherit',
  'top:6px',
  'width:150px',
  'flex-flow:row nowrap',
  'will-change:transform, opacity',
  'color:var(--fgColor-muted)',
  'color:var(--__N4QdCheV6mGo, #0f1111)',
  'font-family:Telesans Text Regular, arial, sans-serif',
  '-ms-overflow-style:none',
  'height:5px',
  'width:80%',
  'margin-right:0.5rem',
  'background-color:var(--background-color-base, #fff)',
  'display:var(--l_display, var(--container-display))',
  'padding-top:1px',
  '-webkit-transform:scale(1)',
  'padding:12px 16px',
  'z-index:999',
  'border-color:inherit',
  'margin-right:1rem',
  'font-size:36px',
  'left:4px',
  'text-decoration:line-through',
  'height:42px',
  'top:20px',
  '--mdc-ripple-fg-opacity:var(--mdc-ripple-press-opacity, 0.12)',
  'color:rgb(232, 234, 237)',
  'color:#7d8da8',
  'margin-top:0%',
  'min-height:1px',
  'width:13px',
  'padding-bottom:15px',
  'line-height:21px',
  'backface-visibility:hidden',
  'padding-top:15px',
  'font-family:"National 2", "Helvetica Neue", Helvetica, Arial, "Hiragino Sans", "Hiragino Kaku Gothic Pro", "游ゴシック", "游ゴシック体", YuGothic, "Yu Gothic", "ＭＳ ゴシック", "MS Gothic", sans-serif',
  '--container-display:grid',
  '-webkit-box-direction:reverse',
  'right:4px',
  'margin-left:-1px',
  'width:5px',
  'gap:12px',
  'transform:rotate(90deg)',
  'font-size:21px',
  'font-size:0.9em',
  'color:#455f7c',
  'cursor:auto',
  'max-height:4rem',
  '-webkit-align-items:flex-end',
  'height:3px',
  'min-width:auto',
  'z-index:9999',
  'color:#1a73e8',
  'font-weight:100',
  '--tw-bg-opacity:1',
  'width:90px',
  'margin:8px',
  'margin-top:-8px',
  'height:3rem',
  '-webkit-appearance:button',
  'background:rgba(0, 0, 0, 0)',
  'color:rgba(0, 0, 0, 0.38)',
  'border-bottom-color:transparent',
  'max-height:99999px',
  'left:5px',
  'margin-left:32px',
  'font-family:"Google Sans", roboto, "Noto Sans Myanmar UI", arial, sans-serif',
  'color:#232a31',
  'font-weight:var(--spl-font-weight-body)',
  'opacity:0.2',
  'height:90px',
  'height:inherit',
  'color:#3c4043',
  'height:1.25rem',
  'border-color:#000',
  'flex-flow:column',
  'background-color:var(--color_surface)',
  'color:var(--bui_color_foreground)',
  'min-width:240px',
  'overflow-wrap:normal',
  'text-indent:0',
  'text-indent:-9999px',
  'background-color:var(--channel-color-light)',
  'font-family:Arial, Roboto, sans-serif',
  'letter-spacing:0.314px',
  'font-family:Marr Sans, Arial, Roboto, sans-serif',
  'max-width:unset',
  '-webkit-align-self:stretch',
  'width:180px',
  'bottom:-1px',
  'line-height:25px',
  'justify-self:start',
  'font-variation-settings:"wght" 525, "opsz" 60',
  'max-height:0',
  'text-decoration:inherit',
  'height:2rem',
  '-ms-transform:translate(-50%, -50%)',
  'line-height:33px',
  'line-height:var(--bui_font_body_2_line-height)',
  'width:72px',
  'width:128px',
  'flex-direction:column-reverse',
  'padding:12px 0',
  'margin:0 2px',
  'margin-top:-5px',
  'width:4px',
  'width:1.25rem',
  'padding-left:30px',
  'margin-bottom:2rem',
  'margin-top:48px',
  'animation-fill-mode:forwards',
  'top:15px',
  'color:var(--gm3-sys-color-primary, #0b57d0)',
  'line-break:auto',
  'color:#1351b4',
  'color:#0071c2',
  '--container-layout-type:grid-container-layout',
  '-ms-flex-item-align:center',
  'font-size:2em',
  'right:50%',
  'border-color:rgba(0, 0, 0, 0.12)',
  'color:#0c0c0c',
  'display:contents',
  'padding:5px 10px',
  'margin:0 0 10px',
  '-webkit-transform:scalex(-1)',
  'letter-spacing:0rem',
  'height:1.5rem',
  'font-size:80%',
  'width:var(--mdc-ripple-fg-size, 100%)',
  'height:var(--mdc-ripple-fg-size, 100%)',
  'margin-left:15px',
  'color:#757575',
  '--tw-text-opacity:1',
  '--bg-gradient:none',
  'height:52px',
  'min-height:auto',
  'opacity:0.12',
  'margin-bottom:1em',
  '-webkit-backface-visibility:hidden',
  'color:var(--yt-spec-icon-active-other)',
  'color:var(--yt-spec-icon-inactive)',
  'height:unset',
  'transform-origin:center center',
  'outline-width:2px',
  'font-feature-settings:normal',
  'cursor:text',
  'flex-flow:row wrap',
  'letter-spacing:0.25px',
  'border-bottom-width:0',
  'table-layout:fixed',
  'line-height:2',
  'font-size:var(--bui_font_body_2_font-size)',
  'padding-left:1rem',
  'font-size:1.5em',
  'font-size:1.4em',
  'color:#0a0a0a',
  'font-size:0.95rem',
  'margin-left:-16px',
  'margin-bottom:1px',
  'margin:4px',
  'width:320px',
  'direction:rtl',
  'padding-left:2px',
  'top:-0.5em',
  'border-radius:1rem',
  'font-family:cnn_sans_display, helveticaneue, Helvetica, Arial, Utkal, sans-serif',
  'line-height:1.17',
  'left:12px',
  'margin-top:-3px',
  'padding-bottom:6px',
  'top:7px',
  'padding-bottom:32px',
  'font-size:0.8em',
  'grid-template-columns:1fr',
  'font-family:var(--bui_font_body_2_font-family)',
  'color:#008347',
  'background-color:white',
  '-webkit-transform:scale(0)',
  'font-size:0.625rem',
  'border-radius:var(--borderRadius-medium)',
  'border-top-color:transparent',
  'font-family:"Font Awesome 5 Free"',
  'background-color:var(--yt-spec-10-percent-layer)',
  'font-weight:var(--ytd-user-comment-font-weight)',
  'letter-spacing:var(--ytd-user-comment-letter-spacing)',
  'font-family:var(--ytd-user-comment-font-family)',
  'padding-bottom:3px',
  'height:150px',
  'resize:none',
  'width:400px',
  'bottom:100%',
  'border-radius:0.5rem',
  '-moz-box-shadow:none',
  'border-bottom:1px solid #ddd',
  'transform:rotate(-45deg)',
  'font-size:19px',
  'right:15px',
  'font-weight:var(--bui_font_body_2_font-weight)',
  'width:240px',
  '-webkit-flex-direction:row-reverse',
  'height:128px',
  'padding-top:40px',
  'width:220px'
];
