import type { Metadata } from "next";
import { headers } from "next/headers";
import {
  LocalizedStringProvider,
  createLocalizedStringDictionary,
} from "@adobe/react-spectrum/i18n";

const dictionary = createLocalizedStringDictionary([
  "@react-spectrum/datepicker",
]);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const nonce = headers().get("x-nonce");
  console.log("nonce", nonce);
  return (
    <html lang="en">
      <body>
        <LocalizedStringProvider
          locale="en"
          dictionary={dictionary}
          nonce={nonce ?? ""}
        />
        {children}
      </body>
    </html>
  );
}
